// systemd.go: render hexplus-proxy-<name>.service for each configured
// proxy. The unit just invokes `hexplus proxy run <name>` so the
// supervisor side stays inside the binary - no extra exec layer, no
// shell wrappers.

package proxy

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/lolyhexey/hexplus/internal/paths"
)

const systemdUnitDir = "/etc/systemd/system"

// proxyUnitTemplate matches the hardening profile of the
// openvpn/squid/dropbear units so a misbehaving proxy can't reach
// outside its sandbox.
const proxyUnitTemplate = `# Generated by hexplus proxy add. Manual edits are preserved if you
# write a drop-in at /etc/systemd/system/{{.UnitName}}.d/override.conf;
# 'hexplus proxy add --force' rewrites this top-level file.
[Unit]
Description=HEXPLUS proxy '{{.Name}}' (port {{.Port}}, default {{.DefaultHost}})
Documentation=https://github.com/lolyhexey/hexplus-v2
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{.SelfPath}} proxy run {{.Name}}
Restart=on-failure
RestartSec=5s
StartLimitIntervalSec=0
LimitNOFILE=65536
ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
`

// WriteUnit creates (or updates) the systemd unit for one proxy and
// runs daemon-reload. Idempotent: byte-equal content is skipped.
// Reload failure is reported but not fatal so writes go through in
// containers without dbus.
func WriteUnit(cfg Config) (path string, written bool, reloadErr error, err error) {
	tmpl, err := template.New("proxy-unit").Parse(proxyUnitTemplate)
	if err != nil {
		return "", false, nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, struct {
		Name        string
		Port        int
		DefaultHost string
		UnitName    string
		SelfPath    string
	}{
		Name:        cfg.Name,
		Port:        cfg.Port,
		DefaultHost: cfg.DefaultHost,
		UnitName:    cfg.UnitName(),
		SelfPath:    paths.SelfPath,
	}); err != nil {
		return "", false, nil, fmt.Errorf("render template: %w", err)
	}

	dest := filepath.Join(systemdUnitDir, cfg.UnitName())
	if err := os.MkdirAll(systemdUnitDir, 0o755); err != nil {
		return dest, false, nil, fmt.Errorf("mkdir %s: %w", systemdUnitDir, err)
	}
	if existing, readErr := os.ReadFile(dest); readErr == nil && bytes.Equal(existing, buf.Bytes()) {
		return dest, false, nil, nil
	}
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o644); err != nil {
		return dest, false, nil, fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, dest); err != nil {
		_ = os.Remove(tmp)
		return dest, false, nil, fmt.Errorf("rename %s -> %s: %w", tmp, dest, err)
	}

	return dest, true, daemonReload(), nil
}

// RemoveUnit drops the per-proxy unit. Missing files are tolerated so
// the call is idempotent.
func RemoveUnit(cfg Config) (path string, removed bool, reloadErr error, err error) {
	dest := filepath.Join(systemdUnitDir, cfg.UnitName())
	if err := os.Remove(dest); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return dest, false, nil, nil
		}
		return dest, false, nil, fmt.Errorf("remove %s: %w", dest, err)
	}
	return dest, true, daemonReload(), nil
}

// daemonReload is the same shell-out the service package uses; we
// keep our own copy to avoid the package importing service (which
// would create a longer dependency chain than this small file needs).
func daemonReload() error {
	cmd := exec.Command("systemctl", "daemon-reload")
	out, err := cmd.CombinedOutput()
	if err != nil {
		if errors.Is(err, exec.ErrNotFound) {
			return errors.New("systemctl not found; is systemd installed?")
		}
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
