package ovpnspread

import (
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/lolyhexey/hexplus/internal/atomicfile"
	"github.com/lolyhexey/hexplus/internal/ovpninstance"
	"github.com/lolyhexey/hexplus/internal/service"
)

// Overridable for tests.
var (
	dropInPath   = filepath.Join(service.SystemdUnitDir, ovpninstance.PrimaryUnit+".d", "hexplus-ovpnspread.conf")
	daemonReload = func() error { return exec.Command("systemctl", "daemon-reload").Run() }
)

// dropInContent makes the primary want the workers: they start with it at
// boot and on every start, and (through their own PartOf) stop and restart
// with it. A disabled primary therefore keeps the workers down as well.
func dropInContent(ws []ovpninstance.Instance) string {
	units := make([]string, 0, len(ws))
	for _, w := range ws {
		units = append(units, w.UnitName())
	}
	return "# Generated by hexplus (OpenVPN menu [11]): the CPU-spreading workers\n" +
		"# start, stop and restart with the primary.\n" +
		"[Unit]\nWants=" + strings.Join(units, " ") + "\n"
}

// writeDropIn writes the primary's drop-in for ws, reloading systemd only
// when it changed.
func writeDropIn(ws []ovpninstance.Instance) error {
	want := dropInContent(ws)
	if cur, err := os.ReadFile(dropInPath); err == nil && string(cur) == want {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(dropInPath), 0o755); err != nil {
		return err
	}
	if err := atomicfile.Write(dropInPath, []byte(want), 0o644); err != nil {
		return err
	}
	return daemonReload()
}

func removeDropIn() error {
	err := os.Remove(dropInPath)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	_ = os.Remove(filepath.Dir(dropInPath)) // only if empty: an operator's override.conf stays
	return daemonReload()
}
