// bootstrap.go: lay down the minimum configuration each service needs to
// start cleanly on a fresh box.
//
// Scope decisions:
//   - We write configs only if they're missing. An existing /etc/squid/squid.conf
//     belongs to the operator, not to us; the same goes for /etc/openvpn/*.
//   - Squid gets a minimal HTTP-CONNECT-only config sized to the HEXPLUS
//     workload (localnet + localhost, no caching).
//   - Dropbear's host keys are deliberately NOT generated here; the unit
//     passes `-R` to dropbear so it creates them lazily on first start.
//     We just make sure /etc/dropbear/ exists and is writable.
//   - OpenVPN needs a CA + server cert + DH params, which is a separate
//     decision the operator makes via `hexplus pki init` (P2.x). On a
//     fresh box without that command run, openvpn refuses to start with
//     a clear "ca.crt not found" - that's intentional, not a bug.

package service

import (
	"fmt"
	"os"
	"path/filepath"
)

// BootstrapResult records the per-path outcome so install can render it.
type BootstrapResult struct {
	Written []string
	Skipped []string
}

// BootstrapConfigs writes default configs and creates state directories
// for the three services. Idempotent: existing files are never rewritten.
func BootstrapConfigs() (BootstrapResult, error) {
	var res BootstrapResult

	if err := os.MkdirAll("/etc/squid", 0o755); err != nil {
		return res, fmt.Errorf("mkdir /etc/squid: %w", err)
	}
	if err := os.MkdirAll("/etc/dropbear", 0o700); err != nil {
		return res, fmt.Errorf("mkdir /etc/dropbear: %w", err)
	}
	if err := os.MkdirAll("/etc/openvpn", 0o755); err != nil {
		return res, fmt.Errorf("mkdir /etc/openvpn: %w", err)
	}

	// Squid: minimal HTTP CONNECT proxy, no caching, journal-routed logs.
	wrote, err := writeIfMissing("/etc/squid/squid.conf", []byte(defaultSquidConf), 0o644)
	if err != nil {
		return res, err
	}
	res.append("/etc/squid/squid.conf", wrote)

	return res, nil
}

func (r *BootstrapResult) append(path string, wrote bool) {
	if wrote {
		r.Written = append(r.Written, path)
	} else {
		r.Skipped = append(r.Skipped, path)
	}
}

// writeIfMissing writes data to dest with mode mode IFF the file doesn't
// exist yet. Returns true when a write happened, false when the existing
// file was preserved. Atomic via tmp+rename, like writeAtomic.
func writeIfMissing(dest string, data []byte, mode os.FileMode) (bool, error) {
	if _, err := os.Stat(dest); err == nil {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return false, fmt.Errorf("mkdir parent of %s: %w", dest, err)
	}
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, data, mode); err != nil {
		return false, fmt.Errorf("write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, dest); err != nil {
		_ = os.Remove(tmp)
		return false, fmt.Errorf("rename %s -> %s: %w", tmp, dest, err)
	}
	return true, nil
}

// defaultSquidConf is the starter config HEXPLUS lays down. It mirrors
// what `Modulos/conexao` writes in HEXPLUS v1 minus features we don't
// auto-enable (cache_dir, refresh_pattern beyond defaults, payload
// shaping). The TUI menu in a later phase rewrites this file with the
// per-deployment knobs the operator picks.
const defaultSquidConf = `# Generated by hexplus install.
#
# This is a minimal starter config. The TUI menu rewrites this file when
# the operator picks a port / payload / response code; until then, squid
# listens on 3128 for localhost + RFC1918 networks only.
http_port 3128

# Standard ACL set sourced from the upstream squid.conf example.
acl localhost src 127.0.0.1/32
acl to_localhost dst 127.0.0.0/8
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow CONNECT SSL_ports
http_access allow localhost
http_access allow localnet
http_access deny all

# Banner / privacy. visible_hostname is what shows up in error pages.
visible_hostname hexplus
via off
forwarded_for off
pipeline_prefetch off

# No caching - HEXPLUS uses squid as a connect proxy, not a cache.
cache deny all

# Disable unlinkd (cache-file deletion helper - not needed with cache deny all).
# Squid 3.3.x does not support "none" keyword; /bin/true exits immediately
# which is harmless since we never write cache files.
unlinkd_program /bin/true

# Suppress logging - stdout/stderr are journald pipes; open(2) on /dev/stdout
# returns ENXIO in a systemd service, and stdio: prefix requires Squid 3.4+.
access_log none
cache_log /dev/null

# Squid refuses to run as root even when explicitly requested; use nobody which
# exists on all Linux systems. Port binding happens before the privilege drop.
cache_effective_user nobody

# Override compiled-in data paths to dirs we create at install time so Squid
# does not require system squid package files.
icon_directory /var/spool/squid/icons
error_directory /var/spool/squid/errors
logfile_daemon /usr/lib/squid/log_file_daemon

pid_filename /var/spool/squid/squid.pid
coredump_dir /var/spool/squid
`
