// systemd.go: write systemd unit files for every Service in All() under
// /etc/systemd/system/ and ask systemd to pick them up.
//
// We do NOT auto-enable or auto-start units on install. The user does that
// explicitly via `hexplus service enable <name>` (P2.2) so a fresh install
// doesn't surprise anyone by opening listening ports without consent.

package service

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/lolyhexey/hexplus/internal/paths"
)

// SystemdUnitDir is where systemd reads admin-installed units from. We
// deliberately use /etc/systemd/system rather than /lib/systemd/system so
// the user can override any of our units with a drop-in without us
// stomping their edit on the next install.
const SystemdUnitDir = "/etc/systemd/system"

// unitTemplate is rendered once per Service. Kept short on purpose - if
// we need StandardOutput=journal, OOMScoreAdjust, etc., add them as
// dedicated fields on Service, not as template-only text, so the
// behavior is discoverable from Go code.
const unitTemplate = `# Generated by hexplus install. Manual edits are preserved if you write
# a drop-in at /etc/systemd/system/{{.UnitName}}.d/override.conf;
# hexplus only ever rewrites this top-level file.
[Unit]
Description={{.DisplayName}}
Documentation=https://github.com/lolyhexey/hexplus-v2
After={{join .After " "}}
Wants={{join .After " "}}

[Service]
Type=simple
ExecStart={{.Binary}}{{range .Args}} {{.}}{{end}}
Restart=on-failure
RestartSec=5s
LimitNOFILE=131072
# Bound the blast radius of a misbehaving service. None of ours need
# anything outside the standard read-only system view.
ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
`

// WriteResult records what WriteUnits did so the caller can render a
// detailed install report. ReloadWarning is non-nil when the unit files
// landed cleanly but `systemctl daemon-reload` failed (typical in
// containers without a running PID 1 systemd); the install is still
// usable, the user just needs to reload by hand on first real boot.
type WriteResult struct {
	Written       []string
	Skipped       []string
	ReloadWarning error
}

// WriteUnits renders every service's unit file into SystemdUnitDir and
// runs `systemctl daemon-reload` to make systemd notice them.
// Idempotent: if a unit's contents already match the desired output,
// it isn't rewritten and the file's mtime isn't touched.
//
// daemon-reload failure is reported via ReloadWarning, not err: on disk
// the units are correct either way, and on a properly-booted systemd
// host the reload succeeds. The split lets `hexplus install` succeed
// in containers and chroots that don't have dbus reachable.
func WriteUnits() (WriteResult, error) {
	written, skipped, err := writeUnitFiles()
	if err != nil {
		return WriteResult{Written: written, Skipped: skipped}, err
	}
	res := WriteResult{Written: written, Skipped: skipped}
	if len(written) > 0 {
		if rerr := daemonReload(); rerr != nil {
			res.ReloadWarning = rerr
		}
	}
	return res, nil
}

func writeUnitFiles() (written []string, skipped []string, err error) {
	return writeUnitFilesFor(All())
}

// writeUnitFilesFor is the underlying writer that both writeUnitFiles
// (all services) and the per-service lazy install path use.
func writeUnitFilesFor(svcs []Service) (written []string, skipped []string, err error) {
	tmpl, err := template.New("unit").Funcs(template.FuncMap{
		"join": strings.Join,
	}).Parse(unitTemplate)
	if err != nil {
		return nil, nil, fmt.Errorf("parse unit template: %w", err)
	}

	if err := os.MkdirAll(SystemdUnitDir, 0o755); err != nil {
		return nil, nil, fmt.Errorf("mkdir %s: %w", SystemdUnitDir, err)
	}

	for _, svc := range svcs {
		dest := filepath.Join(SystemdUnitDir, svc.UnitName)
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, svc); err != nil {
			return written, skipped, fmt.Errorf("render %s: %w", svc.UnitName, err)
		}

		// Compare against existing content; skip the rewrite if identical
		// so we don't bump mtime and confuse `systemctl list-unit-files`
		// caching on busy systems.
		if existing, readErr := os.ReadFile(dest); readErr == nil && bytes.Equal(existing, buf.Bytes()) {
			skipped = append(skipped, dest)
			continue
		}

		if err := writeAtomic(dest, buf.Bytes(), 0o644); err != nil {
			return written, skipped, fmt.Errorf("write %s: %w", dest, err)
		}
		written = append(written, dest)
	}
	return written, skipped, nil
}

// RemoveUnits is the uninstall counterpart - drops the units and reloads
// systemd. Missing files are treated as already-gone.
func RemoveUnits() (removed []string, err error) {
	any := false
	for _, svc := range All() {
		dest := filepath.Join(SystemdUnitDir, svc.UnitName)
		if err := os.Remove(dest); err != nil {
			if errors.Is(err, os.ErrNotExist) {
				continue
			}
			return removed, fmt.Errorf("remove %s: %w", dest, err)
		}
		removed = append(removed, dest)
		any = true
	}
	if any {
		_ = daemonReload() // best-effort; the units are already gone
	}
	return removed, nil
}

// SystemdAvailable reports whether systemd is the active init on this box.
// We use the presence of /run/systemd/system - this is the same probe
// systemd's own sd_booted(3) uses, and it's true on any systemd PID 1
// regardless of whether dbus, journald, etc. happen to be running.
func SystemdAvailable() bool {
	st, err := os.Stat("/run/systemd/system")
	return err == nil && st.IsDir()
}

// CreateDropbearSymlinks lays down LibDir/dropbear -> LibDir/dropbearmulti
// (and dropbearkey, scp likewise) so systemd ExecStart can use a path
// whose basename triggers the right dispatch inside the multi binary.
// Called from install.Install after the embed extracts the multi binary.
func CreateDropbearSymlinks() error {
	target := paths.LibDir + "/dropbearmulti"
	for _, name := range []string{"dropbear", "dropbearkey", "scp"} {
		link := paths.LibDir + "/" + name
		// Remove first so we don't error out if a previous install
		// left a stale symlink pointing elsewhere.
		if err := os.Remove(link); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("clear %s: %w", link, err)
		}
		if err := os.Symlink(target, link); err != nil {
			return fmt.Errorf("symlink %s -> %s: %w", link, target, err)
		}
	}
	return nil
}

// writeAtomic writes data to dest via a tempfile+rename so a crash mid-write
// can't leave a partial unit on disk that systemd would then refuse to parse.
func writeAtomic(dest string, data []byte, mode os.FileMode) error {
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, data, mode); err != nil {
		return err
	}
	if err := os.Rename(tmp, dest); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// daemonReload runs systemctl daemon-reload, mapping a missing systemctl
// binary into a clear error message. Output is captured so a failure
// surfaces in the caller's error instead of silently going to stderr.
func daemonReload() error {
	cmd := exec.Command("systemctl", "daemon-reload")
	out, err := cmd.CombinedOutput()
	if err != nil {
		if errors.Is(err, exec.ErrNotFound) {
			return errors.New("systemctl not found in PATH; is systemd installed?")
		}
		return fmt.Errorf("%w: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
