// Package speedlimit manages the per-session bandwidth caps applied to
// OpenVPN clients via tc HTB on tun + ifb — one independent cap per
// OpenVPN instance (the primary server.conf plus each extra port).
//
// State lives in /etc/openvpn/hexplus-speedlimit.conf, one line per
// instance: "main=10" caps the primary, "2=20" caps extra instance #2.
// A missing key means that port is unshaped. The learn-address shell
// script keys off $dev — tun0/tun1 belong to the primary (dynamic "dev
// tun" allocation), tunN (N≥2) belongs to instance N.
//
// server*.conf files carry a `learn-address <script>` line whenever ANY
// cap is configured; the script exits 0 without shaping when its own
// instance has no entry, so a single inject covers every combination.
package speedlimit

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const (
	// ConfPath stores the per-instance Mbps values, one "key=N" per line.
	ConfPath = "/etc/openvpn/hexplus-speedlimit.conf"

	// ScriptPath is the learn-address hook. OpenVPN calls it with
	// "add|update|delete <tun_ip> <cn>" every time a client joins/leaves.
	ScriptPath = "/usr/local/bin/hexplus-learn-address"

	// MainKey is the config key for the primary server.conf instance.
	MainKey = "main"

	// learnAddressLine is injected into server*.conf while any cap is on,
	// and stripped when all are off. String is matched exactly for removal.
	learnAddressLine = "learn-address " + ScriptPath
)

// Limits maps an instance key (MainKey or the instance ID as a string,
// e.g. "2") to its Mbps cap. Only keys with cap > 0 are present.
type Limits map[string]int

// LoadAll parses ConfPath. Missing file → empty map. The pre-per-port
// "mbps=N" form is read as MainKey for backward compatibility.
func LoadAll() Limits {
	out := Limits{}
	data, err := os.ReadFile(ConfPath)
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		v, err := strconv.Atoi(strings.TrimSpace(val))
		if err != nil || v <= 0 {
			continue
		}
		key = strings.TrimSpace(key)
		if key == "mbps" { // legacy single-value form
			key = MainKey
		}
		out[key] = v
	}
	return out
}

// LoadFor returns the cap for one instance key, 0 when unshaped.
func LoadFor(key string) int { return LoadAll()[key] }

// SetLimit sets (mbps > 0) or clears (mbps == 0) one instance's cap and
// keeps the on-disk artifacts consistent: script deployed and
// learn-address injected while any cap exists, everything stripped when
// the last cap is cleared.
func SetLimit(key string, mbps int) error {
	if mbps < 0 {
		return fmt.Errorf("mbps ต้องเป็น 0 ขึ้นไป (ได้ %d)", mbps)
	}
	limits := LoadAll()
	if mbps == 0 {
		delete(limits, key)
	} else {
		limits[key] = mbps
	}
	if len(limits) == 0 {
		if err := os.Remove(ConfPath); err != nil && !os.IsNotExist(err) {
			return err
		}
		return StripServerConf()
	}
	if err := deployScript(); err != nil {
		return err
	}
	if err := writeConf(limits); err != nil {
		return err
	}
	return InjectServerConf()
}

// DisableAll clears every cap and strips the learn-address hooks.
func DisableAll() error {
	if err := os.Remove(ConfPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return StripServerConf()
}

func writeConf(limits Limits) error {
	keys := make([]string, 0, len(limits))
	for k := range limits {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# Generated by hexplus. Edit via menu → OPENVPN → [8].\n")
	b.WriteString("# main = primary server.conf; a number = extra instance ID.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%d\n", k, limits[k])
	}
	return os.WriteFile(ConfPath, []byte(b.String()), 0o644)
}

func deployScript() error {
	return os.WriteFile(ScriptPath, []byte(learnAddressScript), 0o755)
}

// serverConfs returns every OpenVPN server config the shaper should hook:
// the primary server.conf plus every extra-instance server<N>.conf.
func serverConfs() []string {
	matches, _ := filepath.Glob("/etc/openvpn/server*.conf")
	return matches
}

// InjectServerConf makes sure every server*.conf contains the
// learn-address line (idempotent). Silently does nothing when no config
// exists yet — pki.Init hasn't run, there's no meaningful action to take.
func InjectServerConf() error {
	for _, path := range serverConfs() {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		conf := string(data)
		if strings.Contains(conf, learnAddressLine) {
			continue
		}
		conf = strings.TrimRight(conf, "\n") + "\n" + learnAddressLine + "\n"
		if err := os.WriteFile(path, []byte(conf), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// StripServerConf removes any learn-address line pointing at our script
// from every server*.conf. Idempotent; safe when the line isn't present.
func StripServerConf() error {
	for _, path := range serverConfs() {
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		var out []string
		for _, line := range strings.Split(string(data), "\n") {
			if strings.TrimSpace(line) == learnAddressLine {
				continue
			}
			out = append(out, line)
		}
		if err := os.WriteFile(path, []byte(strings.Join(out, "\n")), 0o644); err != nil {
			return err
		}
	}
	return nil
}
