// Package speedlimit manages the per-session bandwidth cap applied to
// OpenVPN clients via tc HTB on tun + ifb.
//
// State lives in /etc/openvpn/hexplus-speedlimit.conf (single line "mbps=N").
// Presence of the file with mbps>0 means "shape every session at N Mbps
// up + N Mbps down"; missing file or mbps=0 means "no shaping".
//
// The actual tc calls happen inside the learn-address shell script this
// package writes to /usr/local/bin/hexplus-learn-address. server.conf gains
// a `learn-address <path>` line while shaping is enabled and loses it when
// disabled — the caller wires that in via pki.SetLearnAddress().
package speedlimit

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

const (
	// ConfPath stores the operator-chosen Mbps value. One line: "mbps=N".
	ConfPath = "/etc/openvpn/hexplus-speedlimit.conf"

	// ScriptPath is the learn-address hook. OpenVPN calls it with
	// "add|update|delete <tun_ip> <cn>" every time a client joins/leaves.
	ScriptPath = "/usr/local/bin/hexplus-learn-address"

	// ServerConfPath is /etc/openvpn/server.conf. Speedlimit toggles a
	// single `learn-address` directive in it.
	ServerConfPath = "/etc/openvpn/server.conf"

	// learnAddressLine is injected into server.conf when shaping is on,
	// and stripped when off. String is matched exactly for removal.
	learnAddressLine = "learn-address " + ScriptPath
)

// Load returns the currently configured cap in Mbps, or 0 if shaping is off
// (missing file, malformed content, or explicit mbps=0).
func Load() int {
	data, err := os.ReadFile(ConfPath)
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "mbps=") {
			v, err := strconv.Atoi(strings.TrimPrefix(line, "mbps="))
			if err != nil || v < 0 {
				return 0
			}
			return v
		}
	}
	return 0
}

// Save writes the given Mbps value (must be > 0). Deploys the learn-address
// script alongside the config so an out-of-band edit of the conf file that
// bumps mbps still lands on a working shaper.
func Save(mbps int) error {
	if mbps <= 0 {
		return fmt.Errorf("mbps must be > 0 (got %d)", mbps)
	}
	if err := deployScript(); err != nil {
		return err
	}
	body := fmt.Sprintf("# Generated by hexplus. Edit via menu → OPENVPN → [8].\nmbps=%d\n", mbps)
	return os.WriteFile(ConfPath, []byte(body), 0o644)
}

// Disable removes the config file (shaping off). Leaves the learn-address
// script in place — cheap to keep, and if someone reads server.conf they
// won't see a dangling reference to a missing binary if they re-enable.
func Disable() error {
	if err := os.Remove(ConfPath); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

func deployScript() error {
	return os.WriteFile(ScriptPath, []byte(learnAddressScript), 0o755)
}

// InjectServerConf makes sure server.conf contains the learn-address line
// (idempotent). Returns nil silently if server.conf doesn't exist yet —
// pki.Init hasn't run, and there's no meaningful action to take.
func InjectServerConf() error {
	data, err := os.ReadFile(ServerConfPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	conf := string(data)
	if strings.Contains(conf, learnAddressLine) {
		return nil
	}
	conf = strings.TrimRight(conf, "\n") + "\n" + learnAddressLine + "\n"
	return os.WriteFile(ServerConfPath, []byte(conf), 0o644)
}

// StripServerConf removes any learn-address line pointing at our script.
// Idempotent; safe to call when the line isn't present.
func StripServerConf() error {
	data, err := os.ReadFile(ServerConfPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	var out []string
	for _, line := range strings.Split(string(data), "\n") {
		if strings.TrimSpace(line) == learnAddressLine {
			continue
		}
		out = append(out, line)
	}
	return os.WriteFile(ServerConfPath, []byte(strings.Join(out, "\n")), 0o644)
}
