package pki

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/lolyhexey/hexplus/internal/atomicfile"
)

// AuthScriptPath is where we write the fallback password-auth script.
const AuthScriptPath = OpenVPNDir + "/hexplus-auth.sh"

// authScript validates username/password against /etc/shadow using
// openssl passwd, and rejects expired accounts. It needs bash, getent,
// openssl, date, sed, cut and awk; any of them missing makes it reject.
const authScript = `#!/bin/bash
CREDFILE="$1"
USERNAME=$(sed -n '1p' "$CREDFILE")
PASSWORD=$(sed -n '2p' "$CREDFILE")

ENTRY=$(getent shadow "$USERNAME" 2>/dev/null)
HASH=$(printf '%s\n' "$ENTRY" | cut -d: -f2)
[ -z "$HASH" ] && exit 1
case "$HASH" in "!"|"*"|"!!"*) exit 1 ;; esac

# Account expiry: shadow field 8, in days since 1970-01-01, set by
# 'useradd -e' and 'chage -E'. Same rule as pam_unix: expired once today
# reaches that day. Empty or -1 means never; anything else malformed fails,
# and so does a clock we cannot read. More than 9 digits is millions of
# years away and counts as never.
EXPIRE=$(printf '%s\n' "$ENTRY" | cut -d: -f8)
case "$EXPIRE" in
    ''|-1) ;;
    *[!0-9]*) exit 1 ;;
    *)
        NOW=$(date +%s 2>/dev/null)
        case "$NOW" in ''|*[!0-9]*) exit 1 ;; esac
        [ ${#EXPIRE} -le 9 ] && [ $((NOW / 86400)) -ge "$EXPIRE" ] && exit 1
        ;;
esac

ALG=$(echo "$HASH"  | awk -F'$' '{print $2}')
SALT=$(echo "$HASH" | awk -F'$' '{print $3}')
# With SHA_CRYPT_MIN/MAX_ROUNDS in login.defs the hash is
# $6$rounds=N$salt$digest; openssl passwd takes "rounds=N$salt" as the salt.
case "$SALT" in
    rounds=*) SALT="$SALT\$$(echo "$HASH" | awk -F'$' '{print $4}')" ;;
esac

# The password goes to openssl on stdin (printf is a shell builtin): on the
# command line it was readable by every local user in /proc/<pid>/cmdline.
case "$ALG" in
    6|5|1) COMPUTED=$(printf '%s\n' "$PASSWORD" | openssl passwd -"$ALG" -salt "$SALT" -stdin 2>/dev/null) ;;
    *) exit 1 ;;
esac

[ "$COMPUTED" = "$HASH" ] && exit 0 || exit 1
`

const defaultServerConf = `# Generated by hexplus pki init.
# Edit then run 'hexplus service restart openvpn' to apply.
# 'hexplus pki init --force' overwrites this file.

port 1194
proto tcp
dev tun
sndbuf 0
rcvbuf 0

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

dh none
ecdh-curve secp384r1

topology subnet
server 10.8.0.0 255.255.0.0
ifconfig-pool-persist ipp.txt

push "redirect-gateway def1"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 1.1.1.1"

keepalive 10 120

data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

persist-key
persist-tun
client-to-client
script-security 2
verify-client-cert none
username-as-common-name
auth-user-pass-verify /etc/openvpn/hexplus-auth.sh via-file

max-clients 65535

status /var/log/openvpn-status.log 5
status-version 2
verb 3
duplicate-cn
`

// dnsLines maps the DNS choice (1-7 as string) to push directives —
// mirrors v1 conexao's DNS case block exactly (including option 7).
var dnsLines = map[string][]string{
	"1": {}, // system resolvers — operator edits /etc/resolv.conf manually
	"2": {`push "dhcp-option DNS 8.8.8.8"`, `push "dhcp-option DNS 8.8.4.4"`},
	"3": {`push "dhcp-option DNS 208.67.222.222"`, `push "dhcp-option DNS 208.67.220.220"`},
	"4": {`push "dhcp-option DNS 1.1.1.1"`, `push "dhcp-option DNS 1.0.0.1"`},
	"5": {`push "dhcp-option DNS 74.82.42.42"`},
	"6": {`push "dhcp-option DNS 64.6.64.6"`, `push "dhcp-option DNS 64.6.65.6"`},
	"7": {`push "dhcp-option DNS 189.38.95.95"`, `push "dhcp-option DNS 216.146.36.36"`},
}

// authDirectives returns the server.conf lines that authenticate clients
// with hexplus-auth.sh.
//
// There is deliberately no PAM-plugin branch: the embedded OpenVPN is built
// with --disable-plugins (build/Dockerfile.openvpn), so a "plugin <so>
// login" line makes it exit at startup with "Unrecognized option ...
// plugin". An earlier version emitted that line whenever an
// openvpn-plugin-auth-pam.so happened to exist on the host.
//
// Note: we deliberately omit "user nobody / group nogroup" — those
// directives prevent the auth script from reading /etc/shadow. v1
// conexao also omits them.
func authDirectives() string {
	return "script-security 2\nverify-client-cert none\nusername-as-common-name\n" +
		"auth-user-pass-verify " + AuthScriptPath + " via-file"
}

// writeAuthLines writes hexplus-auth.sh and returns the server.conf lines
// that reference it.
func writeAuthLines() string {
	_ = atomicfile.Write(AuthScriptPath, []byte(authScript), 0o700)
	return authDirectives()
}

// EnsureAuthScript rewrites hexplus-auth.sh when it is installed but differs
// from the embedded version, so fixes reach hosts installed by an older
// release (the script is otherwise only written when a server config is
// generated). OpenVPN runs the script afresh for every login, so no restart
// is needed. A host without the script (OpenVPN not installed) is left
// alone.
func EnsureAuthScript() error { return ensureAuthScriptAt(AuthScriptPath) }

func ensureAuthScriptAt(path string) error {
	cur, err := os.ReadFile(path)
	if err != nil || string(cur) == authScript {
		return nil
	}
	return atomicfile.Write(path, []byte(authScript), 0o700)
}

// pamPluginLine matches the line releases up to v2.1.5 wrote instead of
// auth-user-pass-verify when openvpn-plugin-auth-pam.so existed on the host.
var pamPluginLine = regexp.MustCompile(`^plugin\s+\S*openvpn-plugin-auth-pam\.so\s+login$`)

// repairPluginConf replaces that plugin line with the hexplus-auth.sh
// directives (adding only the ones the config lacks) and reports whether it
// changed anything. Any other plugin line is the operator's and left alone.
func repairPluginConf(conf string) (string, bool) {
	lines := strings.Split(conf, "\n")
	has := func(directive string) bool {
		for _, l := range lines {
			if f := strings.Fields(l); len(f) > 0 && f[0] == directive {
				return true
			}
		}
		return false
	}
	var out []string
	changed := false
	for _, l := range lines {
		if !pamPluginLine.MatchString(strings.TrimSpace(l)) {
			out = append(out, l)
			continue
		}
		if !changed {
			if !has("script-security") {
				out = append(out, "script-security 2")
			}
			if !has("auth-user-pass-verify") {
				out = append(out, "auth-user-pass-verify "+AuthScriptPath+" via-file")
			}
		}
		changed = true
	}
	return strings.Join(out, "\n"), changed
}

// RepairPluginConfs fixes every /etc/openvpn/server*.conf an older release
// wrote with the PAM plugin line. The embedded OpenVPN is built without
// plugin support and refuses to start with it, so those instances have been
// down since they were installed; the same releases never wrote
// hexplus-auth.sh either, so it is written here too. It returns the configs
// it changed; their units need a (re)start.
func RepairPluginConfs() ([]string, error) { return repairPluginConfsIn(OpenVPNDir, AuthScriptPath) }

func repairPluginConfsIn(dir, script string) ([]string, error) {
	confs, err := filepath.Glob(filepath.Join(dir, "server*.conf"))
	if err != nil {
		return nil, err
	}
	var fixed []string
	var errs []error
	for _, path := range confs {
		raw, err := os.ReadFile(path)
		if err != nil {
			errs = append(errs, err)
			continue
		}
		out, changed := repairPluginConf(string(raw))
		if !changed {
			continue
		}
		if err := atomicfile.Write(script, []byte(authScript), 0o700); err != nil {
			errs = append(errs, err)
			continue
		}
		if err := atomicfile.Write(path, []byte(out), 0o644); err != nil {
			errs = append(errs, err)
			continue
		}
		fixed = append(fixed, path)
	}
	return fixed, errors.Join(errs...)
}

// WriteServerConf overwrites /etc/openvpn/server.conf with the operator's
// chosen port, protocol, and DNS. Called by the install-flow menu after
// pki.Init() has already written certs and a default conf.
func WriteServerConf(port int, proto, dnsChoice, _ string) error {
	dns, ok := dnsLines[strings.TrimSpace(dnsChoice)]
	if !ok {
		dns = dnsLines["2"] // default: Google
	}
	dnsPushLines := strings.Join(dns, "\n")
	if dnsPushLines != "" {
		dnsPushLines = "\n" + dnsPushLines
	}

	exitNotify := ""
	if proto == "udp" {
		exitNotify = "\nexplicit-exit-notify 1"
	}

	authLines := writeAuthLines()

	conf := fmt.Sprintf(`port %d
proto %s
dev tun
sndbuf 0
rcvbuf 0

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

dh none
ecdh-curve secp384r1

topology subnet
server 10.8.0.0 255.255.0.0
ifconfig-pool-persist ipp.txt

push "redirect-gateway def1"%s

keepalive 10 120

data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

persist-key
persist-tun
client-to-client
%s
duplicate-cn

max-clients 65535

status /var/log/openvpn-status.log 5
status-version 2
verb 3%s
`, port, proto, dnsPushLines, authLines, exitNotify)

	return os.WriteFile(OpenVPNDir+"/server.conf", []byte(conf), 0o644)
}

// WriteInstanceConf writes /etc/openvpn/server<id>.conf for an extra
// OpenVPN instance. Shares the primary instance's PKI (ca/cert/key/ta)
// and auth setup so every existing user works on the new port without
// re-exporting a profile; only the network identity differs:
//
//	dev tun<id>, subnet 10.<8+id-1>.0.0/16, own ipp/status files.
//
// dnsPush carries the `push "dhcp-option DNS ..."` lines copied from the
// primary conf so both instances hand out the same resolvers.
func WriteInstanceConf(id, port int, proto string, dnsPush []string) error {
	if id < 2 || id > 200 {
		return fmt.Errorf("instance id ต้องอยู่ระหว่าง 2-200 (ได้ %d)", id)
	}
	dnsLines := strings.Join(dnsPush, "\n")
	if dnsLines != "" {
		dnsLines = "\n" + dnsLines
	}
	exitNotify := ""
	if proto == "udp" {
		exitNotify = "\nexplicit-exit-notify 1"
	}
	authLines := writeAuthLines()

	conf := fmt.Sprintf(`# Generated by hexplus (extra OpenVPN instance %d).
# Managed via menu → OPENVPN → พอร์ตเพิ่มเติม.

port %d
proto %s
dev tun%d
sndbuf 0
rcvbuf 0

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

dh none
ecdh-curve secp384r1

topology subnet
server 10.%d.0.0 255.255.0.0
ifconfig-pool-persist ipp%d.txt

push "redirect-gateway def1"%s

keepalive 10 120

data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

persist-key
persist-tun
client-to-client
%s
duplicate-cn

max-clients 65535

status /var/log/openvpn-status%d.log 5
status-version 2
verb 3%s
`, id, port, proto, id, 8+id-1, id, dnsLines, authLines, id, exitNotify)

	return os.WriteFile(fmt.Sprintf("%s/server%d.conf", OpenVPNDir, id), []byte(conf), 0o644)
}

// HasDuplicateCN reports whether the OpenVPN config at path allows several
// sessions per user (MULTILOGIN on). A missing file reads as false.
func HasDuplicateCN(path string) bool {
	raw, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	for _, l := range strings.Split(string(raw), "\n") {
		if strings.TrimSpace(l) == "duplicate-cn" {
			return true
		}
	}
	return false
}

// SetDuplicateCN adds or removes the duplicate-cn line in the OpenVPN config
// at path. The daemon reads it only at start, so the caller restarts it.
func SetDuplicateCN(path string, on bool) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var kept []string
	for _, l := range strings.Split(strings.TrimRight(string(raw), "\n"), "\n") {
		if strings.TrimSpace(l) != "duplicate-cn" {
			kept = append(kept, l)
		}
	}
	if on {
		kept = append(kept, "duplicate-cn")
	}
	return atomicfile.Write(path, []byte(strings.Join(kept, "\n")+"\n"), 0o644)
}
