package pki

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

const defaultServerConf = `# Generated by hexplus pki init.
# Edit then run 'hexplus service restart openvpn' to apply.
# 'hexplus pki init --force' overwrites this file.

port 1194
proto udp
dev tun
sndbuf 0
rcvbuf 0

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

# ECDH instead of DH params: avoids the 5-30 minute DH generation on
# shared VPS cores and matches what modern OpenVPN deployments use.
dh none
ecdh-curve secp384r1

topology subnet
server 10.8.0.0 255.255.0.0

push "redirect-gateway def1"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 1.1.1.1"

keepalive 10 120

# Cipher set covers OpenVPN 2.5+ (data-ciphers negotiation) and 2.4
# fallback (data-ciphers-fallback + cipher).
data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

# Drop privileges after binding the port.
user nobody
group nogroup
persist-key
persist-tun
client-to-client
verify-client-cert none
username-as-common-name

status /var/log/openvpn-status.log
verb 3
duplicate-cn
`

// dnsLines maps the DNS choice (1-7 as string) to push directives —
// mirrors v1 conexao's DNS case block exactly (including option 7).
var dnsLines = map[string][]string{
	"1": {}, // system resolvers — operator edits /etc/resolv.conf manually
	"2": {`push "dhcp-option DNS 8.8.8.8"`, `push "dhcp-option DNS 8.8.4.4"`},
	"3": {`push "dhcp-option DNS 208.67.222.222"`, `push "dhcp-option DNS 208.67.220.220"`},
	"4": {`push "dhcp-option DNS 1.1.1.1"`, `push "dhcp-option DNS 1.0.0.1"`},
	"5": {`push "dhcp-option DNS 74.82.42.42"`},
	"6": {`push "dhcp-option DNS 64.6.64.6"`, `push "dhcp-option DNS 64.6.65.6"`},
	"7": {`push "dhcp-option DNS 189.38.95.95"`, `push "dhcp-option DNS 216.146.36.36"`},
}

// FindPAMPlugin returns the absolute path to openvpn-plugin-auth-pam.so,
// trying common distro locations and falling back to `find`. Returns ""
// if not found.
func FindPAMPlugin() string {
	candidates := []string{
		"/usr/lib/openvpn/openvpn-plugin-auth-pam.so",
		"/usr/lib64/openvpn/openvpn-plugin-auth-pam.so",
		"/usr/lib/x86_64-linux-gnu/openvpn/openvpn-plugin-auth-pam.so",
		"/usr/lib/aarch64-linux-gnu/openvpn/openvpn-plugin-auth-pam.so",
	}
	for _, p := range candidates {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	out, err := exec.Command("find", "/usr", "-type", "f",
		"-name", "openvpn-plugin-auth-pam.so").Output()
	if err == nil {
		line := strings.SplitN(strings.TrimSpace(string(out)), "\n", 2)[0]
		if line != "" {
			return line
		}
	}
	return ""
}

// WriteServerConf overwrites /etc/openvpn/server.conf with the operator's
// chosen port, protocol, and DNS. Called by the install-flow menu after
// pki.Init() has already written certs and a default conf.
func WriteServerConf(port int, proto, dnsChoice, _ string) error {
	dns, ok := dnsLines[strings.TrimSpace(dnsChoice)]
	if !ok {
		dns = dnsLines["2"] // default: Google
	}
	dnsPushLines := strings.Join(dns, "\n")
	if dnsPushLines != "" {
		dnsPushLines = "\n" + dnsPushLines
	}

	exitNotify := ""
	if proto == "udp" {
		exitNotify = "\nexplicit-exit-notify 1"
	}

	pamPlugin := FindPAMPlugin()
	pamLine := ""
	if pamPlugin != "" {
		pamLine = "\nplugin " + pamPlugin + " login"
	}

	conf := fmt.Sprintf(`port %d
proto %s
dev tun
sndbuf 0
rcvbuf 0

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

dh none
ecdh-curve secp384r1

topology subnet
server 10.8.0.0 255.255.0.0

push "redirect-gateway def1"%s

keepalive 10 120

data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

user nobody
group nogroup
persist-key
persist-tun
client-to-client
verify-client-cert none
username-as-common-name%s
duplicate-cn

status /var/log/openvpn-status.log
verb 3%s
`, port, proto, dnsPushLines, pamLine, exitNotify)

	return os.WriteFile(OpenVPNDir+"/server.conf", []byte(conf), 0o644)
}
