// serverconf.go: the default /etc/openvpn/server.conf hexplus lays
// down once PKI is initialized.
//
// Design choices vs the v1 conexao.bash output:
//   - No `dh dh.pem`. We tell OpenVPN `dh none` + `ecdh-curve secp384r1`
//     instead, which sidesteps the 5-30 minute DH parameter generation
//     on shared VPS cores. ECDHE-only handshakes are what every modern
//     TLS deployment uses anyway.
//   - No `comp-lzo yes`. Deprecated in OpenVPN 2.5, removed in 2.6;
//     VORACLE makes it actively unsafe.
//   - `verify-client-cert none` instead of the removed
//     `client-cert-not-required`. Same end-state (auth handled by
//     auth-user-pass-verify) but accepted by 2.5+ servers.
//   - `data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC` + a fallback
//     so OpenVPN 2.4 clients still negotiate the CBC cipher our v1
//     deployments shipped.
//
// The TUI menu later rewrites this file with the operator's port /
// proto / DNS / push directives; this template is a working starting
// point, not the final form.

package pki

const defaultServerConf = `# Generated by hexplus pki init.
# Edit then run 'hexplus service restart openvpn' to apply.
# 'hexplus pki init --force' overwrites this file.

port 1194
proto udp
dev tun

ca   /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key  /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

# ECDH instead of DH params: avoids the 5-30 minute DH generation on
# shared VPS cores and matches what modern OpenVPN deployments use.
dh none
ecdh-curve secp384r1

topology subnet
server 10.8.0.0 255.255.255.0
# No ifconfig-pool-persist on purpose: HEXPLUS allows a single user to
# connect from multiple devices (duplicate-cn below), and OpenVPN refuses
# to persist a pool that gets re-issued under the same CN.

push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 1.1.1.1"

keepalive 10 120

# Cipher set covers OpenVPN 2.5+ (data-ciphers negotiation) and 2.4
# fallback (data-ciphers-fallback + cipher).
data-ciphers AES-256-GCM:AES-128-GCM:AES-256-CBC
data-ciphers-fallback AES-256-CBC
cipher AES-256-CBC
auth SHA256

# Drop privileges after binding the port.
user nobody
group nogroup
persist-key
persist-tun

# Phase 4 default: cert-only auth. Clients authenticate by presenting
# an x509 cert signed by our CA - per-user certs are issued via
# 'hexplus user add' (P5). Once user management lands we'll switch to
# verify-client-cert + auth-user-pass-verify for the username/password-
# on-top-of-cert flow HEXPLUS v1 customers expect.
duplicate-cn

status /var/log/openvpn-status.log
verb 3
explicit-exit-notify 1
`
